### ISSUE TITLE
Sorry you need to use yarn

### ISSUE THREAD

**Issue by trickydisco78** [gvaldambrini/gatsby-starter-bulma-storybook#1]
Just clones the repo and ran the command.

Have tried using gatsby new and yarn install and both error ![image](https://user-images.githubusercontent.com/3627429/39529466-a767ceb2-4e1e-11e8-9d43-8dae87a01872.png)

I have yarn 1.6 running on windows 7

**Comment by trickydisco78** [comment]
I;m guessing because process.env.npm_execpath doesn;'t exist in my enviroment?

**Comment by gvaldambrini** [comment]
It might be. I've never run it on Windows, so it probably needs some adjustment to work on it. I'll have a look asap but of course if you have any idea it'd be appreciated.

**Comment by trickydisco78** [comment]
Cheers. I've taken the preinstall part out of package.json and got it to run fine now

**Comment by gvaldambrini** [comment]
Fixed in 083996d. Thank you for the report!

**Comment by trickydisco78** [comment]
Thanks! no worries.
